# **A Byte Of R**
**_Rajaomalala Sendra A._**

<font color="blue">**Dedication**</font>
.....
### Table of content in A byte of R
Welcome 
Who reads A Byte of R? 
License
Read Now
Download
Preface ....................................................................................................................
1. Who This Book Is For .................................................................................
2. Official Website ............................................................................................
3. Something To Think About ..........................................................................
Introduction
    Features of R
3. Installation 
3.1. Installation on Windows ............................................................................
3.1.1. DOS Prompt ...................................................................................
3.1.2. Running Python prompt on Windows .............................................
3.2. Installation on Mac OS X ..........................................................................
3.3. Installation on GNU/Linux .........................................................................
3.4. Summary ...................................................................................................
4. First Steps ...........................................................................................................
4.1. Using The Interpreter Prompt ...................................................................
4.2. Choosing An Editor ...................................................................................
4.3. PyCharm ...................................................................................................
4.4. Vim ............................................................................................................
4.5. Emacs .......................................................................................................
4.6. Using A Source File .................................................................................
4.7. Getting Help ..............................................................................................
4.8. Summary 
5. Basics ..................................................................................................................
5.1. Comments .................................................................................................
5.2. Literal Constants .......................................................................................
5.3. Numbers ................................................................................................... 38
5.4. Strings ....................................................................................................... 38
5.4.1. Single Quote ...................................................................................
5.4.2. Double Quotes ................................................................................
5.4.3. Triple Quotes ..................................................................................
5.4.4. Strings Are Immutable ....................................................................
5.4.5. The format method .........................................................................
5.4.6. Escape Sequences .........................................................................
5.4.7. Raw String ......................................................................................
Variable .....................................................................................................
Identifier Naming .......................................................................................
Data Types ...............................................................................................
Object ........................................................................................................
How to write R programs ................................................................. 
5.10. For Rstudio ..........................................................................................
5.11. For other editors .....................................................................................
5.12. Example: Using Variables And Literal Constants ....................................
5.13. Logical And Physical Line .......................................................................
5.14. Indentation ..............................................................................................
5.15. Summary .................................................................................................
6. Operators and Expressions ................................................................................
6.1. Operators ..................................................................................................
6.2. Shortcut for math operation and assignment ............................................
6.3. Evaluation Order .......................................................................................
6.4. Changing the Order Of Evaluation ...........................................................
6.5. Associativity ..............................................................................................
6.6. Expressions ...............................................................................................
6.7. Summary ...................................................................................................
7. Control Flow ........................................................................................................
7.1. The if statement ........................................................................................
7.2. The while Statement .................................................................................
7.3. The for loop ..............................................................................................
7.4. The break Statement ................................................................................
7.5. The continue Statement ............................................................................
7.6. Summary ...................................................................................................
8. Functions .............................................................................................................
8.1. Function Parameters .................................................................................
8.2. Local Variables .........................................................................................
8.3. The global statement ................................................................................ 67
8.4. Default Argument Values .......................................................................... 68
8.5. Keyword Arguments .................................................................................. 69
8.6. VarArgs parameters .................................................................................. 70
8.7. The return statement ................................................................................ 70
8.8. DocStrings ................................................................................................ 71
8.9. Summary ................................................................................................... 73
9. Modules ............................................................................................................... 74
9.1. Byte-compiled .pyc files ............................................................................ 76
9.2. The from ... import statement ................................................................... 76
9.3. A module’s name .................................................................................... 76
9.4. Making Your Own Modules ...................................................................... 77
9.5. The dir function ......................................................................................... 79
9.6. Packages .................................................................................................. 80
9.7. Summary ................................................................................................... 81
10. Data Structures ................................................................................................. 82
10.1. List .......................................................................................................... 82
10.2. Quick Introduction To Objects And Classes ........................................... 82
10.3. Tuple ....................................................................................................... 84
10.4. Dictionary ................................................................................................ 86
10.5. Sequence ................................................................................................ 88
10.6. Set ........................................................................................................... 91
10.7. References .............................................................................................. 91
10.8. More About Strings ................................................................................. 93
10.9. Summary ................................................................................................. 94
11. Problem Solving ................................................................................................ 95
11.1. The Problem ........................................................................................... 95
11.2. The Solution ............................................................................................ 96
11.3. Second Version ...................................................................................... 99
11.4. Third Version ........................................................................................ 101
11.5. Fourth Version ...................................................................................... 103
11.6. More Refinements ................................................................................. 105
11.7. The Software Development Process .................................................... 105
11.8. Summary ............................................................................................... 106
12. Object Oriented Programming ........................................................................ 107
12.1. The self ................................................................................................. 108
12.2. Classes ................................................................................................. 10
12.4. The init method ............................................................................... 110
12.5. Class And Object Variables .................................................................. 111
12.6. Inheritance ............................................................................................
12.7. Summary ...............................................................................................
13. Input and Output .............................................................................................
13.1. Input from user .....................................................................................
13.1.1. Homework exercise ....................................................................
13.2. Files ......................................................................................................
13.3. Pickle ....................................................................................................
13.4. Unicode .................................................................................................
13.5. Summary ...............................................................................................
14. Exceptions .......................................................................................................
14.1. Errors ....................................................................................................
14.2. Exceptions ............................................................................................. 114
14.3. Handling Exceptions .............................................................................
14.4. Raising Exceptions ...............................................................................
14.5. Try ... Finally ........................................................................................
14.6. The with statement ...............................................................................
14.7. Summary ...............................................................................................
15. Standard Library .............................................................................................
15.1. sys module ............................................................................................
15.2. logging module .....................................................................................
15.3. Module of the Week Series ..................................................................
15.4. Summary ...............................................................................................
16. More ................................................................................................................
16.1. Passing tuples around ..........................................................................
16.2. Special Methods ...................................................................................
16.3. Single Statement Blocks .......................................................................
16.4. Lambda Forms ......................................................................................
16.5. List Comprehension ..............................................................................
16.6. Receiving Tuples and Dictionaries in Functions ...................................
16.7. The assert statement ............................................................................
16.8. Decorators .............................................................................................
16.9. Differences between Python 2 and Python 3 ........................................
16.10. Summary .............................................................................................
17. What Next .......................................................................................................
17.1. Next Projects ........................................................................................
17.2. Example Code ...................................................................................
17.3. Advice ................................................................................................... 142
17.4. Videos ................................................................................................... 142
17.5. Questions and Answers ........................................................................
17.6. Tutorials ................................................................................................
17.7. Discussion .............................................................................................
17.8. News .....................................................................................................
17.9. Installing libraries ..................................................................................
17.10. Creating a Website .............................................................................
17.11. Graphical Software .............................................................................
17.12. Summary of GUI Tools .......................................................................
17.13. Various Implementations .....................................................................
17.14. Functional Programming (for advanced readers) ................................
17.15. Summary .............................................................................................
18. Appendix: FLOSS ........................................................................................... 142
19. Appendix: History Lesson ...............................................................................
19.1. Status Of The Book ..............................................................................
20. Appendix: Revision History .......................................